<a href="https://colab.research.google.com/github/SyrVyn/goocollab/blob/Numpy%26panda/%5BNotebook_TyBullington%5D_Module_10_(NumPy_%26_Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Getting Started with Python!**

## NumPy

In the previous notebook we learnt the basics of Python and why it's so popular for application in AI. We also learnt about the different data types available in Python, what modules and packages are along with different control options. Now let's get started with **NumPy** (short for Numerical'Num' Python'Py')  one of the most popular packages available in Python for performing scientfic calculcations especially those related to arrays. Let's get started!

## Arrays

NumPy arrays in python are basically grids of values of the same data type. Each element of a NumPy array has a non-negative index associated with it. When dealing with arrays, we come across a useful term called **shape** which gives the size of the array along each dimension. So why do we use NumPy array instead of standard Python lists? In Data Science calculations, NumPy arrays take up smaller memory consumption and better runtime behavior this is important as commonly, we deal with a large amount of data and the difference in processing Python lists and NumPy arrays will add up to a significant difference. NumPy also contains multi-dimensional array and matrix data structures and can perform several mathematical operations on arrays such as trigonometric, statistical, and algebraic routines.

In [ ]:
# importing numpy package
import numpy as np

In [ ]:
arrA = np.array([1, 2, 3])  # initializing an array with the elements given in the brackets
print(arrA)

[1 2 3]


Let's check the datatype for the array 'a'

In [ ]:
print(type(arrA))# write your code for checking the datatype here

<class 'numpy.ndarray'>


In [ ]:
# Creating an array with more than one dimension
arrB = np.array([[1, 2], [3, 4]])
print(arrB)

[[1 2]
 [3 4]]


In [ ]:
print(type([[1, 2], [3, 4]]))  # write the code that verifies [[1, 2], [3, 4]] is a list

<class 'list'>


In [ ]:
# let's check the shape of the arrays created so far
print("Shape of array 'arrA' is:", (arrA.shape))
print("Shape of array 'arrB' is:", (arrB.shape))

Shape of array 'arrA' is: (3,)
Shape of array 'arrB' is: (2, 2)


In [ ]:
# creating a 3-d array - addition
arrC = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arrC.shape)

(3, 2, 2)


In [ ]:
# accessing elements of the array using the index
print(arrA[0], arrA[1], arrA[2])
print(arrB[0][0])
#printing the first row first, first column element

1 2 3
1


In [ ]:
# another way of printing a particular element of an array
print(arrB[0,1])

2


In [ ]:
# using the arange function to create an array
arangeC = np.arange(4)  # prints the first four elements as 0 onwards by default
print(arangeC)
arrangeD = np.arange(1,7)  # specifying start point and end point
print(arrangeD)

[0 1 2 3]
[1 2 3 4 5 6]


In [ ]:
# Create the following array with given shape (3, 4). Name the array 'new'
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
new = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Slicing is being used to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; new_sub is the following array of shape (2, 2):
new_sub = new[:2, 1:3]
print(new_sub)

[[2 3]
 [6 7]]


**Integer array indexing**

When you index into numpy arrays using slicing, the resulting array will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Do you recall slicing? We have gone through this in the previous notebook! Remember, indexes in Python always starts from 0 for the first element.

Here is an example:

In [ ]:
arrA = np.array([[1,2], [3, 4], [5, 6]])

# Given the following, this is output of the above, can you see how you would get [1 4 5]?
# For the value of '1' it is at position 0,0 which is the first 'box' and the first 'item' in the 'box'
# For the vlaue of '4' it is at the position of 1,1 which is the second 'box' and the second 'item' in the 'box'
# Can you now figure out how you would get the value of '5'?

print(np.array([arrA[0, 0], arrA[1, 1], arrA[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [ ]:
# The above can also be written as:
# arrA[0,0] '1'
# arrA[1,1] '4'
# arrA[2,0] '5'
# This is an Example of integer array indexing. Look closely can you tell the difference between this statement and the last?
subOfA = (arrA[[0, 1, 2], [0, 1, 0]])  # Do you now see how array indexing is done and how it relates to the previous statements?


print(subOfA)  # Prints "[1 4 5]"
print(subOfA.shape)  # Shape is 3

[1 4 5]
(3,)


We can also use integer indexing to mutate specific elements of an array

In [ ]:
# Mutate first element from each row of arrA
arrA[np.arange(3), 0] += 10

print(arrA)

[[21  2]
 [23  4]
 [25  6]]


## Datatypes in NumPy Arrays

In [ ]:
roll_no = np.array([23, 46])   # Let numpy choose the datatype
print(roll_no.dtype)         # Prints "int64"

marks = np.array([65.5, 88.0])   # Let numpy choose the datatype
print(marks.dtype)             # Prints "float64"

int64
float64


In [ ]:
ArrX = np.array([1, 2], dtype=np.int8)   # Force a particular datatype
print(ArrX.dtype)                         # Prints "int64"

int8


**Array Mathematics**

Basic mathematical operations are available on arrays in an elementwise manner. This can be done using either operators like (+,-,* etc.) or as built-in functions within the package itself.

In [ ]:
ArrX = np.array([[1, 2], [3, 4]], dtype=np.float64)
ArrY = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(ArrX + ArrY)
print(np.add(ArrX, ArrY))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# write a code to create two arrays X & Y with the following elements and print their difference
# ArrX = [[13.0 7.0]
#        [4.0 47.0]]
# ArrY = [[16.0 14.0]
#        [1.0 23.0]]

In [ ]:
ArrX = np.array([[13.0, 7.0], [4.0, 47.0]], dtype=np.float64)
ArrY = np.array([[16.0, 14.0], [1.0, 23.0]], dtype=np.float64)
print (ArrX-ArrY)
print(np.subtract(ArrX, ArrY))

[[-3. -7.]
 [ 3. 24.]]
[[-3. -7.]
 [ 3. 24.]]


In [ ]:
# to perform elementwise multiplication
print(ArrX * ArrY)
print(np.multiply(ArrX,ArrY))

[[ 208.   98.]
 [   4. 1081.]]
[[ 208.   98.]
 [   4. 1081.]]


Note that this is different from performing matrix multiplication. The * operator is only used for elementwise multiplication.

In [ ]:
# to perform elementwise division
print(ArrX / ArrY)
print(np.divide(ArrX, ArrY))

Sorting NumPy Arrays

In [ ]:
arrA = np.array([1, 2, 3, 4, 5, 2, 1])
print(arrA)

In [ ]:
np.sort(arrA)  # function for sorting elements in ascending order
print(np.sort(arrA))
print(arrA)  # Note that the result is not assigned back to the original array

In [ ]:
# function for sorting elements in descending order
np.flip(np.sort(arrA))
print(np.flip(np.sort(arrA)))

[[25  6]
 [23  4]
 [21  2]]


## Manipulating NumPy Arrays

The function reshape() allows manipulation of shape of array without altering its elements. The syntax for this function is illustrated below

In [ ]:
arrX = np.arange(12)  # creating 12*1 array
print(arrX)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# changing shape from 12*1 to 6*2 array
arrY=arrX.reshape(6,2)
print(arrY)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


Just like concatenation of lists or strings we can concatenate arrays as well. In the following example we concatenate three one-dimensional arrays to one array. The elements of the second array are appended to the first array. After this the elements of the third array are appended.

In [ ]:
arrX = np.array([3, 12])
arrY = np.array([12, 4, 7])
arrZ = np.array([2, 6, 8])
print(arrX)
print(arrY)
print(arrZ)
arrC = np.concatenate((arrX, arrY, arrZ))  # function to perform concatenation
print(arrC)

[ 3 12]
[12  4  7]
[2 6 8]
[ 3 12 12  4  7  2  6  8]


If we are concatenating multidimensional arrays, we can concatenate the arrays according to axis. Arrays must have the same shape to be concatenated with concatenate(). In the case of multidimensional arrays, we can arrange them according to the axis. The default value is axis = 0:

In [ ]:
arrX = np.array([[2, 4], [7, 9]])
print(arrX)
arrX=arrX.reshape(1, 4)
print(arrX)
arrY = np.array([10, 12, 14, 16])
print(arrY)
arrY=arrY.reshape(1, 4)
print(arrY)
arrC = np.concatenate((arrX, arrY), axis=None)
print(arrC)

[[2 4]
 [7 9]]
[[2 4 7 9]]
[10 12 14 16]
[[10 12 14 16]]
[ 2  4  7  9 10 12 14 16]


**Pro-tip**: To have a list of useful functions and commands always at your fingertips you can save this [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) here!

# **Pandas**

Pandas is built on top of NumPy and is one of the most popular open-source packages available in Python. It's main utility lies in providing a large number of functions for handling real world data.

You would not need to fully understand the capabilities of Pandas at present, the examples given are just to demonstrate the some of the useful workings of it. In the later sessions we will go through in full detail about how we would use Pandas in an ML workflow

However, we would suggest going forward, to pay special attention to the syntax and the flow and order of the codes as they are generally always being used in similar fashion.

## Importing Pandas

In [ ]:
# Do you recognize the keywords here? Both import and the library name, such syntax will be common going forward
import pandas as pd


A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

DataFrames accepts many different kinds of inputs, if you would like to learn more, feel free to search online or go to [pandas'](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html) documentation. <br>For the purpose of this example, we shall demonstrate a useful way you can use DataFrames. <br><br>Let's say we are interested in the weather, specifically we are interested in data from [Open Government Data](https://data.gov.in/keywords/weather) and have obtained a file called (JaipurFinalCleanData.csv) <br><br>A Comma-Separated Value or csv file, as the name implies contains a set of data separated by commas, files like these would be familiar to users of Spreadsheet software like Excel or Google Sheet.
<br><br>In this example, we will open a csv file in Python, and load it into a DataFrame.
<br><br> **Bonus Exercise:** Try loading in the file, and follow the rest of the exercise. Use your friend, the search engine and find a way to load your file into Colab!

In [ ]:
# If doing locally using Anaconda for example, the file(csv) should be in same the folder as this notebook.
# This example is expected to have errors without the file being uploaded

# First, create a variable we will call the DataFrame from
DataFrame= pd.read_csv('JaipurFinalCleanData.csv')
print(DataFrame.head)

<bound method NDFrame.head of            date  mean_temperature  max_temperature  min_temperature  \
0    2016-05-04                34               41               27   
1    2016-05-05                31               38               24   
2    2016-05-06                28               34               21   
3    2016-05-07                30               38               23   
4    2016-05-08                34               41               26   
..          ...               ...              ...              ...   
671  2018-03-07                24               32               15   
672  2018-03-08                24               32               15   
673  2018-03-09                26               33               19   
674  2018-03-10                26               34               19   
675  2018-03-11                26               34               18   

     Mean_dew_pt  mean_pressure  max_humidity  min_humidity  max_dew_pt_1  \
0              6        1006.00         

the .head() function by default shows the first 5 rows of a DataFrame, it also helps you to check if the csv file have loaded in correctly.

In [ ]:
# You may also add arguments into the function to display more data as so.
print(DataFrame.tail(20))

           date  mean_temperature  max_temperature  min_temperature  \
656  2018-02-20                23               31               15   
657  2018-02-21                24               33               15   
658  2018-02-22                25               33               17   
659  2018-02-23                25               33               17   
660  2018-02-24                26               33               18   
661  2018-02-25                25               30               20   
662  2018-02-26                22               31               14   
663  2018-02-27                24               32               16   
664  2018-02-28                25               32               18   
665  2018-03-01                27               34               20   
666  2018-03-02                26               33               20   
667  2018-03-03                26               34               19   
668  2018-03-04                25               32               18   
669  2

In [ ]:
# Another useful thing you could do is to check all the datatypes within the dataframe
DataFrame.dtypes

Have you noticed? Using print() on the DataFrame shows many values, but how are are you supposed to make sense of all of them? That is where we might want to do Data Visualization and use graphs, plots and charts to better understand what we are looking at and what we might be looking for. In the following Notebook we shall be looking into a useful and common library, **matplotlib** which helps us with this.